apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: my-app-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: ${DOCKER_REGISTRY}/python-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: my-app-namespace
spec:
  selector:
    app: python-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080